packages:
  - client
  - server
  - shared

allowBuilds:
  cpu-features: false
  electron: true
  electron-winstaller: false
  esbuild: true
  sharp: true
  ssh2: false
  uiohook-napi: false
  unrs-resolver: true
